
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'tmdb'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  # dbname
  tmdb:
    # Applies to all files under models/staging/
    staging:
      +materialized: view

    # Applies to all files under models/marts/
    marts:
      +materialized: table

      # Applies to all files under models/marts/credits
      credits:
        +materialized: table
      
      # Applies to all files under models/marts/movies
      movies:
        +materialized: table
      
      # Applies to all files under models/marts/q_movies
      q_movies:
        +materialized: view

      # Applies to all files under models/marts/score
      score:
        +materialized: view